### ISSUE TITLE
Bug in Sort Passages

### ISSUE THREAD

**Issue by ThomasK81** [ThomasK81/gocite#4]
https://github.com/ThomasK81/gocite/blob/71e7a6c14663212fa73c01a7c7115305cc9d8d9b/gocite.go#L364

Is a real mistake. It needs to be 

```
nextPassageID := w.Passages[cursor].Next. PassageID 
cursor, _ =   GetIndexByID(nextPassageID, w)
```

If you want add error handling, too.

**Comment by ace280** [comment]
Should be fixed with https://github.com/ThomasK81/gocite/releases/tag/2.0.0
